version: "3.9"

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      device: /home/roudouch/data/db
      o: bind 
      # When you use a bind mount, a file or directory on the host machine
      # is mounted into a container.
      
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      device: /home/roudouch/data/wp
      o: bind

networks:
  Docker-Network:
    name: Docker-Network
    # a bridge network uses a software bridge which allows containers connected to the same bridge network to communicate,
    # while providing isolation from containers which are not connected to that bridge network. 
    driver: bridge 

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariaDB/
    image: mariadb:database
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - Docker-Network
    restart: unless-stopped # unless-stopped, Similar to always , except that when the container is stopped (manually or otherwise), it is not restarted even after .

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress:website
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - Docker-Network
    restart: unless-stopped 
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx:webServer
    depends_on:
      - staticpage
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - Docker-Network
    restart: unless-stopped
  
  staticpage:
    container_name: staticpage
    build: ./requirements/static_page/
    image: static_page:webServer
    ports:
      - 8080:8080
    networks:
      - Docker-Network
    restart: unless-stopped