version: "3"

services:
  db:
    image: mariadb:10
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "rachid"
      MYSQL_PASSWORD: "1234"
      MYSQL_ROOT_PASSWORD: root
    restart: always

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpress
    ports: ['9000:80']
    links: ['db:db']
    volumes:
      - ./wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: rachid
      WORDPRESS_DB_PASSWORD: "1234"
    restart: always

volumes:
  db_data: {}