version: "3.9"

volumes:
  db_data:
    driver: local 

networks:
  Docker-Network:
    name: Docker-Network
    driver: bridge

services:
  db:
    container_name: mariadb
    build: ./requirements/mariaDB/
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - Docker-Network
    restart: always

  wordpress:
    container_name: wordpress
    #build: ./requirements/wordpress/
    image: wordpress:latest
    depends_on:
      - db
    ports:
      - 9000:80
    volumes:
      - ./data/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_DB_USER:  "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - Docker-Network
    restart: always