version: "3.9"

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      device: /root/Inception/data/db
      o: bind
      
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      device: /root/Inception/data/wp
      o: bind

networks:
  Docker-Network:
    name: Docker-Network
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariaDB/
    image: mariadb
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - Docker-Network
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    env_file:
      - .env
    networks:
      - Docker-Network
    restart: unless-stopped # unless-stopped, Similar to always , except that when the container is stopped (manually or otherwise), it is not restarted even after .
  
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    depends_on:
      - wordpress
    ports:
      - 443:443
    volumes:
      - wp:/var/www/html
    networks:
      - Docker-Network
    restart: unless-stopped