FROM debian:buster
# update and upgrade the apk packages and install nginx and openssl
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y nginx && apt install -y openssl

COPY ./config/default /etc/nginx/sites-available/default
# generate the ssl certificate
RUN mkdir /etc/nginx/ssl

RUN openssl req -new -newkey rsa:2048 -nodes -x509 -days 730 \
    -out /etc/nginx/ssl/roudouch.csr \
    -keyout /etc/nginx/ssl/roudouch.key \
    -subj "/C=MA/ST=Béni Mellal-Khénifra/L=Khouribga/O=1337COMPANY/OU=1337/CN=42.fr"

# keep the container running by running nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]