FROM debian:latest
# update and upgrade the apk packages and install nginx and openssl
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y nginx && apt install -y openssl


# copy the nginx.conf file to the /etc/nginx/nginx.conf
COPY ./config/nginx.conf /etc/nginx/nginx.conf
#copy index.html to the /var/www/html/index.html
COPY ./index.html /var/www/html/
# restart the nginx service
RUN service nginx restart


# keep the container running by running nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]