FROM debian:buster
# update and upgrade the apk packages and install nginx and openssl
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y nginx && apt install -y openssl


# copy the nginx.conf file to the /etc/nginx/nginx.conf
COPY ./config/nginx.conf /etc/nginx/conf.d/default.conf

# generate the ssl certificate
RUN mkdir /etc/nginx/ssl
RUN openssl req -new -newkey rsa:2048 -nodes -x509 -days 730 \
    -out /etc/nginx/ssl/roudouch.csr \
    -keyout /etc/nginx/ssl/roudouch.key \
    -subj "/C=MA/ST=Béni Mellal-Khénifra/L=Khouribga/O=1337COMPANY/OU=1337/CN=42.fr"

#copy index.html to the /var/www/html/index.html
COPY ./index.html /var/www/html/index.html

# restart the nginx service
RUN service nginx restart


# keep the container running by running nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]