FROM debian:buster

RUN apt -y update && apt -y upgrade && apt install -y \
    mariadb-server

EXPOSE 3306

COPY ./tools/mariadb.sql /var/www/
COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/

RUN chmod 644 /etc/mysql/mariadb.conf.d/50-server.cnf
RUN service mysql start && mysql -u root < /var/www/mariadb.sql

CMD ["mysqld_safe"]

# mysqld_safe is the recommended way to start a mysqld server on Unix. mysqld_safe 
# adds some safety features such as restarting the server when an error ...